name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
    paths-ignore:
      - 'README.md'

permissions:
  actions: write
  contents: read

jobs:
  cancel-previous-runs:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    permissions:
      actions: write
      contents: read
    defaults:
      run:
        shell: bash
    steps:
      - name: Ensure GitHub CLI is installed
        run: |
          if ! command -v gh &> /dev/null; then
            sudo apt-get update && sudo apt-get install -y gh
          fi
      - name: Cancel Previous Runs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CURRENT_RUN_ID=${{ github.run_id }}
          RUNS=$(gh api repos/${{ github.repository }}/actions/runs --jq ".workflow_runs | map(select(.head_branch == \"${{ github.ref_name }}\" and .status == \"in_progress\" and .id != $CURRENT_RUN_ID)) | .[].id")
          for RUN_ID in $RUNS; do
            gh api repos/${{ github.repository }}/actions/runs/$RUN_ID/cancel -X POST
          done

  checkout:
    runs-on: ubuntu-latest
    needs: cancel-previous-runs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  setup-python:
    runs-on: ubuntu-latest
    needs: checkout

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

  install-dependencies:
    runs-on: ubuntu-latest
    needs: setup-python
    defaults:
      run:
        shell: bash
    steps:
      - name: Check if requirements.txt exists
        run: |
          if [ ! -f requirements.txt ]; then
            echo "requirements.txt not found. Failing early."
            exit 1
          fi
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  run-tests:
    runs-on: ubuntu-latest
    needs: install-dependencies

    steps:
      - name: Run tests
        run: pytest

  additional-tests:
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
      - name: Run additional tests
        run: |
          pytest --cov
          pytest --flake8

  integration-tests:
    runs-on: ubuntu-latest
    needs: additional-tests
    defaults:
      run:
        shell: bash
    steps:
      - name: Check if integration tests directory exists
        run: |
          if [ ! -d tests/integration ]; then
            echo "No integration tests directory found. Skipping."
            exit 0
          fi
      - name: Run integration tests
        run: pytest tests/integration

  build-and-push:
    runs-on: ubuntu-latest
    needs: integration-tests
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}

  ssh-test:
    runs-on: ubuntu-latest
    needs: additional-tests
    defaults:
      run:
        shell: bash
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "echo 'SSH connection successful'"

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    defaults:
      run:
        shell: bash
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
      - name: Pull repository on server
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
          DEPLOY_DIRECTORY: ${{ secrets.DEPLOY_DIRECTORY }}
        run: |
          ssh $VPS_USER@$VPS_HOST "
            if [ ! -d \"$DEPLOY_DIRECTORY\" ]; then
              git clone https://github.com/${{ github.repository }} $DEPLOY_DIRECTORY;
            else
              cd $DEPLOY_DIRECTORY && git pull;
            fi
          "
      - name: Deploy to server
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
          DEPLOY_DIRECTORY: ${{ secrets.DEPLOY_DIRECTORY }}
        run: |
          ssh $VPS_USER@$VPS_HOST "
            cd $DEPLOY_DIRECTORY &&
            docker-compose pull &&
            docker-compose up -d --build
          "

# Reminder: Ensure all required secrets (SSH_PRIVATE_KEY, VPS_HOST, VPS_USER, DEPLOY_DIRECTORY) are set in your repository settings.